<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="VISAI00215L" failures="2" tests="20" name="API Tests - Version 1" time="51.978" errors="0" timestamp="2023-09-07T17:36:52 IST">
  <testcase classname="v1.Get.api.GetMeasurementDataById" name="assertJsonfileWithResponseBody" time="9.146"/>
  <testcase classname="v1.Get.api.GetMeasurementDataById" name="verifybadRequest" time="3.034"/>
  <testcase classname="v1.Get.api.GetMeasurementDataById" name="verifyunauthorized" time="2.845"/>
  <testcase classname="v1.Get.api.GetMeasurementDatabyRange" name="assertthedaterange" time="1.579"/>
  <testcase classname="v1.Get.api.GetMeasurementDatabyRange" name="assertTheIdRange" time="1.541">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at v1.Get.api.GetMeasurementDatabyRange.assertTheIdRange(GetMeasurementDatabyRange.java:159)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- assertTheIdRange -->
  <testcase classname="v1.Get.api.GetMeasurementDatabyRange" name="invalidRangeValue" time="1.499"/>
  <testcase classname="v1.Get.api.GetMeasurementDatabyRange" name="invalidFromOrToValue" time="6.03"/>
  <testcase classname="v1.Get.api.GetMeasurementDatabyRange" name="Unauthorized" time="3.181"/>
  <testcase classname="v1.Get.api.GetMeasurementDataBySku" name="assertTheExteranlJsonToResponseBodyAndStatusCode" time="3.087"/>
  <testcase classname="v1.Get.api.GetMeasurementDataBySku" name="unauthorizedWithMultipeScenarious" time="3.09"/>
  <testcase classname="v1.Get.api.GetMeasurementDataBySku" name="badRequestWithMultipeScenarious" time="2.972"/>
  <testcase classname="v1.Get.api.LatestMeasurementImage" name="Latestmeasurementimage" time="2.048"/>
  <testcase classname="v1.Get.api.LatestMeasurementImage" name="Unauthorized" time="1.377"/>
  <testcase classname="v1.Get.api.LatestMeasurementImage" name="notFound" time="1.535"/>
  <testcase classname="v1.Get.api.ListMeasurementIDandDates" name="Notfound" time="1.326"/>
  <testcase classname="v1.Get.api.ListMeasurementIDandDates" name="ScanIdListEndpoint" time="1.493"/>
  <testcase classname="v1.Get.api.ListMeasurementIDandDates" name="Unauthorized" time="1.367"/>
  <testcase classname="v1.Get.api.MeasurementImagebyID" name="idByImage" time="1.438">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at credentails.CommonMethods.extractValuesFromImage(CommonMethods.java:95)
at v1.Get.api.MeasurementImagebyID.idByImage(MeasurementImagebyID.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- idByImage -->
  <testcase classname="v1.Get.api.MeasurementImagebyID" name="NoImageFound" time="1.703"/>
  <testcase classname="v1.Get.api.MeasurementImagebyID" name="Unauthorized" time="1.619"/>
</testsuite> <!-- API Tests - Version 1 -->
