<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="VISAI00215L" failures="3" tests="17" name="API Tests - Version 2" time="41.795" errors="0" timestamp="2023-09-07T17:37:34 IST">
  <testcase classname="v2.Get.api.GetMeasurementDataById" name="assertJsonfileToResponseBody" time="9.039"/>
  <testcase classname="v2.Get.api.GetMeasurementDataById" name="verifybadRequest" time="2.97"/>
  <testcase classname="v2.Get.api.GetMeasurementDataById" name="verifyunauthorized" time="3.06"/>
  <testcase classname="v2.Get.api.GetMeasurementDatabyRange" name="assertthedaterange" time="1.461"/>
  <testcase classname="v2.Get.api.GetMeasurementDatabyRange" name="assertTheIdRange" time="1.404">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at v2.Get.api.GetMeasurementDatabyRange.assertTheIdRange(GetMeasurementDatabyRange.java:150)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- assertTheIdRange -->
  <testcase classname="v2.Get.api.GetMeasurementDatabyRange" name="invalidRangeValue" time="1.325"/>
  <testcase classname="v2.Get.api.GetMeasurementDatabyRange" name="invalidFromOrToValue" time="5.74"/>
  <testcase classname="v2.Get.api.GetMeasurementDatabyRange" name="Unauthorized" time="2.965"/>
  <testcase classname="v2.Get.api.LatestMeasurementImage" name="Latestmeasurementimage" time="1.792"/>
  <testcase classname="v2.Get.api.LatestMeasurementImage" name="Unauthorized" time="1.535"/>
  <testcase classname="v2.Get.api.LatestMeasurementImage" name="notFound" time="1.432"/>
  <testcase classname="v2.Get.api.ListMeasurementIDandDates" name="Notfound" time="1.533"/>
  <testcase classname="v2.Get.api.ListMeasurementIDandDates" name="ScanIdList" time="1.562"/>
  <testcase classname="v2.Get.api.ListMeasurementIDandDates" name="Unauthorized" time="1.46"/>
  <testcase classname="v2.Get.api.MeasurementImagebyID" name="VeridyTheIdByImage" time="1.548">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at credentails.CommonMethods.extractValuesFromImage(CommonMethods.java:95)
at v2.Get.api.MeasurementImagebyID.VeridyTheIdByImage(MeasurementImagebyID.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- VeridyTheIdByImage -->
  <testcase classname="v2.Get.api.MeasurementImagebyID" name="testNoImageFound" time="1.479">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at credentails.CommonMethods.imageIdAssert(CommonMethods.java:164)
at v2.Get.api.MeasurementImagebyID.testNoImageFound(MeasurementImagebyID.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testNoImageFound -->
  <testcase classname="v2.Get.api.MeasurementImagebyID" name="Unauthorized" time="1.465"/>
  <testcase classname="v2.Get.api.GetMeasurementDataBySku" name="badRequestWithMultipeScenarious" time="0.0">
    <ignored/>
  </testcase> <!-- badRequestWithMultipeScenarious -->
  <testcase classname="v2.Get.api.GetMeasurementDataBySku" name="assertTheExteranlJsonToResponseBodyAndStatusCode" time="0.0">
    <ignored/>
  </testcase> <!-- assertTheExteranlJsonToResponseBodyAndStatusCode -->
  <testcase classname="v2.Get.api.GetMeasurementDataBySku" name="unauthorizedWithMultipeScenarious" time="0.0">
    <ignored/>
  </testcase> <!-- unauthorizedWithMultipeScenarious -->
</testsuite> <!-- API Tests - Version 2 -->
