<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="VISAI00215L" failures="3" tests="20" name="API Tests - Version 1" time="43.71" errors="0" timestamp="2023-09-06T13:15:17 IST">
  <testcase classname="v1.Get.api.GetMeasurementDataById" name="assertJsonfileWithResponseBody" time="1.489">
    <failure type="java.lang.AssertionError" message="Date value for key &amp;apos;scanned_time&amp;apos; does not match the expected value.">
      <![CDATA[java.lang.AssertionError: Date value for key 'scanned_time' does not match the expected value.
at v1.Get.api.GetMeasurementDataById.compareResponseWithExternalData(GetMeasurementDataById.java:139)
at v1.Get.api.GetMeasurementDataById.assertJsonfileWithResponseBody(GetMeasurementDataById.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- assertJsonfileWithResponseBody -->
  <testcase classname="v1.Get.api.GetMeasurementDataById" name="verifybadRequest" time="3.034"/>
  <testcase classname="v1.Get.api.GetMeasurementDataById" name="verifyunauthorized" time="2.993"/>
  <testcase classname="v1.Get.api.GetMeasurementDatabyRange" name="assertthedaterange" time="1.47"/>
  <testcase classname="v1.Get.api.GetMeasurementDatabyRange" name="assertTheIdRange" time="1.482">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at v1.Get.api.GetMeasurementDatabyRange.assertTheIdRange(GetMeasurementDatabyRange.java:159)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- assertTheIdRange -->
  <testcase classname="v1.Get.api.GetMeasurementDatabyRange" name="invalidRangeValue" time="1.551"/>
  <testcase classname="v1.Get.api.GetMeasurementDatabyRange" name="invalidFromOrToValue" time="6.227"/>
  <testcase classname="v1.Get.api.GetMeasurementDatabyRange" name="Unauthorized" time="3.105"/>
  <testcase classname="v1.Get.api.GetMeasurementDataBySku" name="assertTheExteranlJsonToResponseBodyAndStatusCode" time="3.026"/>
  <testcase classname="v1.Get.api.GetMeasurementDataBySku" name="unauthorizedWithMultipeScenarious" time="2.65"/>
  <testcase classname="v1.Get.api.GetMeasurementDataBySku" name="badRequestWithMultipeScenarious" time="3.044"/>
  <testcase classname="v1.Get.api.LatestMeasurementImage" name="Latestmeasurementimage" time="1.867"/>
  <testcase classname="v1.Get.api.LatestMeasurementImage" name="Unauthorized" time="1.388"/>
  <testcase classname="v1.Get.api.LatestMeasurementImage" name="notFound" time="1.401"/>
  <testcase classname="v1.Get.api.ListMeasurementIDandDates" name="Notfound" time="1.462"/>
  <testcase classname="v1.Get.api.ListMeasurementIDandDates" name="ScanIdListEndpoint" time="1.487"/>
  <testcase classname="v1.Get.api.ListMeasurementIDandDates" name="Unauthorized" time="1.427"/>
  <testcase classname="v1.Get.api.MeasurementImagebyID" name="idByImage" time="1.481">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at credentails.CommonMethods.extractValuesFromImage(CommonMethods.java:95)
at v1.Get.api.MeasurementImagebyID.idByImage(MeasurementImagebyID.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- idByImage -->
  <testcase classname="v1.Get.api.MeasurementImagebyID" name="NoImageFound" time="1.501"/>
  <testcase classname="v1.Get.api.MeasurementImagebyID" name="Unauthorized" time="1.567"/>
</testsuite> <!-- API Tests - Version 1 -->
